[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
somnia = 50312

[dependencies]
"@openzeppelin-contracts" = "5.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
somnia = "https://dream-rpc.somnia.network"

[etherscan]
somnia = { key = "${ETHERSCAN_API_KEY}", chain = 50312, url = "https://somnia-explorer-api-url/" }

# Add chain-specific settings if needed
[profile.somnia]
via_ir = true